backend:
  name: github
  repo: tsantosdok/decap
  use_graphql: true
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "src/content/home.md"
      fields:
        - name: categories
          label: Categories
          widget: test
          separator: __
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}